---
title: "PROYECTO"
output: html_notebook
---

```{r}
setwd("/Users/joelrodriguez/Documents/R/Rdraft")
```

Por si quieren actualizar archivos:
```{r}
# Datos abiertos de Mexico
# download.file('http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip', 'source/dataMx.zip')
# unzip('source/dataMx.zip', exdir = 'source/')
```

Cargar datos:
```{r}
rawMxData <- read.csv('source/201118COVID19MEXICO.csv')
```

Volver columna de datos binaria:
```{r}
# Vivos
rawMxData$FECHA_DEF[rawMxData$FECHA_DEF != '9999-99-99'] <- 0
# Muertos
rawMxData$FECHA_DEF[rawMxData$FECHA_DEF == '9999-99-99'] <- 1
```
0 -> paciente vivo
1 -> paciente muerto

# Filtrar datos

Función por enfermedad:

```{r}
# FUNCION QUE REEMPLAZA 2 (FALSE) CON 0 (FALSE)
coMor <- function(comorbiditiesList){
  comorbidities <- matrix(1:length(rawMxData$FECHA_ACTUALIZACION), ncol = 1)
  comorbidities <- cbind(comorbidities, as.numeric(rawMxData$FECHA_DEF), rawMxData$EDAD)
  colnames(comorbidities) <- c('INDICE', 'DEFUNCION', 'EDAD')
  comorbiditiesAux <- sapply(comorbiditiesList, function(comorbidity){
    return(replace(rawMxData[[comorbidity]], rawMxData[[comorbidity]] == 2, 0))
    })
  comorbidities <- cbind(comorbidities, comorbiditiesAux)
  allDates <- apply(comorbidities[,4:length(comorbidities[1,])], MARGIN = 1, FUN = function(paciente){
    bools <- paciente <= 1
    if(all(bools)){
      return(TRUE)
    }else{
      return(FALSE)
    }
  })
  return(comorbidities[allDates,])
}
```

```{r}
prueba <- coMor(c('OBESIDAD', 'DIABETES', 'NEUMONIA'))
table(prueba[,4:6])
```

```{r}
prueba[,3:5]
```


```{r}
rawMxData$OBESIDAD <-  coMor('OBESIDAD')
```

```{r}
coFrame <- data.frame('Muertos' = as.numeric(rawMxData$FECHA_DEF[rawMxData$OBESIDAD != 98]),
           'Obesos' = rawMxData$OBESIDAD[rawMxData$OBESIDAD != 98],
           'Edad' = rawMxData$EDAD[rawMxData$OBESIDAD != 98])
```
0 -> sin comorbilidad
1 -> con comorbilidad

# Minimos cuadrados

```{r}
reLin <- glm(formula = Muertos~Obesos+Edad, coFrame, family = binomial(link = 'logit'))
summary(reLin)
```

```{r}
coFrame
```


